### PR TITLE
Initial Implementation of a "weighted" spinner

### PR DESCRIPTION
**Pull request by PizzaLovers007**
Added angular velocity and angular drag

### CODE REVIEW

**Comment by itdelatrisu** [comment]
Is this finished? o:

**Comment by PizzaLovers007** [comment]
No sorry, I got busy so I haven't had the time to work on it.

**Comment by itdelatrisu** [comment]
Oh, not a problem.  Was just curious, since I just noticed this now. XD  Thanks for working on it!

**Comment by PizzaLovers007** [comment]
No problem! Hopefully I'll have some time to look at it this weekend.

**Pull request merged**
